/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects_.$id'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects_.$id.index'
import { Route as ProjectsIdDemoRouteImport } from './routes/projects_.$id.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdDemoRoute = ProjectsIdDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$id': typeof BlogIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/projects/$id/demo': typeof ProjectsIdDemoRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog': typeof BlogIndexRoute
  '/projects/$id/demo': typeof ProjectsIdDemoRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$id': typeof BlogIdRoute
  '/projects_/$id': typeof ProjectsIdRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/projects_/$id/demo': typeof ProjectsIdDemoRoute
  '/projects_/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/sitemap.xml'
    | '/blog/$id'
    | '/projects/$id'
    | '/blog/'
    | '/projects/$id/demo'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects'
    | '/resume'
    | '/sitemap.xml'
    | '/blog/$id'
    | '/blog'
    | '/projects/$id/demo'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/sitemap.xml'
    | '/blog/$id'
    | '/projects_/$id'
    | '/blog/'
    | '/projects_/$id/demo'
    | '/projects_/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects_/$id': {
      id: '/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id/': {
      id: '/projects_/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects_/$id/demo': {
      id: '/projects_/$id/demo'
      path: '/demo'
      fullPath: '/projects/$id/demo'
      preLoaderRoute: typeof ProjectsIdDemoRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdDemoRoute: typeof ProjectsIdDemoRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdDemoRoute: ProjectsIdDemoRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
