/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsIdRouteImport } from './routes/projects_.$id'
import { Route as ProjectsIdDemoRouteImport } from './routes/projects_.$id.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdDemoRoute = ProjectsIdDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/demo': typeof ProjectsIdDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/$id/demo': typeof ProjectsIdDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/projects_/$id': typeof ProjectsIdRouteWithChildren
  '/projects_/$id/demo': typeof ProjectsIdDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/projects/$id'
    | '/projects/$id/demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/projects/$id'
    | '/projects/$id/demo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/projects_/$id'
    | '/projects_/$id/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id': {
      id: '/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id/demo': {
      id: '/projects_/$id/demo'
      path: '/demo'
      fullPath: '/projects/$id/demo'
      preLoaderRoute: typeof ProjectsIdDemoRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdDemoRoute: typeof ProjectsIdDemoRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdDemoRoute: ProjectsIdDemoRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
